### DISCUSSION TITLE
YAML front matter font

### DISCUSSION THREAD

**Discussion by canpolat** [Zettlr/Zettlr#2834] [Q&A] [answered]
Under Windows 10, YAML front matter font does not look very good for some non-ASCII characters.

![image](https://user-images.githubusercontent.com/459891/142496230-cf86b04d-5161-40f0-ba2d-1057035014d0.png)

It looks like this is due to `Inconsolata`. I wonder if someone could help me with the custom CSS to switch to `Consolas` (that seems to work)?

![image](https://user-images.githubusercontent.com/459891/142496276-7875e1e9-83ea-4a9f-9774-8591ba1740b0.png)

**Comment by canpolat** [comment, marked as answer]
Just copying the selector from the Inspection tool seems to work, but I'm not sure that it's the right solution:

```css
body #editor .CodeMirror .cm-fenced-code, body .dialog .CodeMirror .cm-fenced-code, body #editor .CodeMirror .cm-stex-mode, body .dialog .CodeMirror .cm-stex-mode {
  font-family: Consolas, monospace
}
```

I'm leaving this here so that others with a similar need can see it.
