### DISCUSSION TITLE
Remove Color from List items with Custom CSS

### DISCUSSION THREAD

**Discussion by Sklanfurt** [Zettlr/Zettlr#2952] [Q&A] [answered]
Hi, 

is it possible to remove the color/style of ordered and unordered list markers (meaning the actual number or "-") with Custom CSS? 

I found something like: 

/* Numberlist numbers are dimmed */
body .cm-formatting.cm-formatting-list.cm-formatting-list-ol {
    color: #E2E2E2;
}

in an old thread here (https://docs.zettlr.com/de/core/custom-css/) but it does not seem to work for me. 

Appreciate any help. Thanks!

**Comment by nathanlesage** [comment, marked as answer]
This custom CSS should do the trick:

```css
body #editor .CodeMirror .cm-formatting-list-ul,
body #editor .CodeMirror .cm-formatting-list-ol,
body.dark #editor .CodeMirror .cm-formatting-list-ul,
body.dark #editor .CodeMirror .cm-formatting-list-ol {
  color: inherit;
}
```
