### DISCUSSION TITLE
CSS for hyperlinks

### DISCUSSION THREAD

**Discussion by IgnacioHeredia** [Zettlr/Zettlr#3025] [Q&A] [answered]
Hi all,

I tried modifying the color of hyperlinks in the editor with no success. Using debug mode I can see that links usually belong to classes `cma`, `cm-link` or `cm-url`, but modifying neither of those in the CSS does translate to changes in the editor.

I'm using Zettlr 2.0.2.

Example of failed code:
```
body.dark .CodeMirror .cma {
   color: rgba(250, 160, 85, 1);
}
```

Any help appreciated, thanks :)

**Comment by nathanlesage** [comment, marked as answer]
I just had a look, seems that the selector is `body.dark #editor .CodeMirror .cma` (with or without the `.dark` depending which mode you want to affect). That selector should work.

**Reply by IgnacioHeredia** [reply]
Awesome, thanks!
I was misled because that code did work for `cm-em` so I thought it might just as well work for `cma`.

If you have time, some time ago I opened a related discussion in #2777. The discussion seems to have been buried under the queue but I still think it is a relevant question that would improve the Editor UX.

Thanks again!

**Reply by nathanlesage** [reply]
Ouh yeah, there is a lot of room for improvement! Feel free to discuss that on Discord and/or change the colors and open a PR! :)

**Comment by IgnacioHeredia** [comment]
Closing old discussions. This works now.
```css
/* Links: .cm-link (markdown link), .cm-url (plain URL) */
body.dark .cm-editor :is(.cm-link, .cm-url) {
   color: rgba(0,204,153, 1);
   text-decoration: none;
}

:is(.cm-link,.cm-url):hover {
  cursor: pointer;
}
```
