### DISCUSSION TITLE
How to use advanced yaml-author options for export

### DISCUSSION THREAD

**Discussion by SergejGleithmann** [Zettlr/Zettlr#4436] [Q&A] [answered]
Hey everyone,

I'm trying to use the 
```yaml
author:
  - name: John Doe
    affiliation: College University
```
YAML-Syntax mentioned in the [Wiki](https://docs.zettlr.com/en/core/yaml-frontmatter/#author). However this exports to
![grafik](https://github.com/Zettlr/Zettlr/assets/110982970/6f9ca8b0-8bd7-4721-a124-2acca1f22ef8)
(Example is from the LaTeX-Export, however this happens with the standard export too.)

Using the reduced author syntax 
```yaml
author: John Doe
```
it works fine.
![grafik](https://github.com/Zettlr/Zettlr/assets/110982970/7aaf8e56-5899-4ce8-af8c-a24962b33f6c)
What am I missing? Thanks in advance!

Full Zettlr-File:
```
---
title: test
author:
  - name: John Doe
    affiliation: College University
...
# Heading
Blabla
```

**Comment by nathanlesage** [comment, marked as answer]
The issue is that the author statements are basically just variables you can set, and whatever you set needs to also be available in the TeX template you're using. So, for example, this is the default author settings for Pandoc's default template:

```tex
\author{$for(author)$$author$$sep$ \and $endfor$}
```

As you can see, it assumes the `author` variable to be a simple list of items, like so:

```yaml
author:
  - First author
  - second author
  - etc ...
```

If you wanted to use, e.g., affiliations as well, you would either need to find a template that already includes the proper variable settings or do it yourself. Taking, say, [this stackoverflow exchange](https://tex.stackexchange.com/questions/214404/add-affiliations-to-the-authors-name-in-the-article-class), one could potentially write something like this and paste it into some tex template:

```tex
$for(author)$
\author[$affiliation$]{$name$}
$endfor$
$for(institution)$
\affil[$number$]{$name$}
$endfor$
```

And use, e.g., the following frontmatter code:

```yaml
author:
  - name: John Doe
    affiliation: 1
  - name: Jane Doe
    affiliation: 2
institution:
  - number: 1
    name: First institution
  - number: 2
    name: Second institution
```

Note, however, that I did not test this code. Also, you may need additional packages.
