### DISCUSSION TITLE
How to increase indentation of bulleted lists

### DISCUSSION THREAD

**Discussion by kethinov** [Zettlr/Zettlr#4642] [Show and tell]
I wrote the following custom CSS rule to increase the indentation of bulleted lists.

I wanted to share it with the community in case anyone else finds it useful:

```css
.cm-line > span.cm-list:first-of-type:not(.cm-meta):not(.cm-code-mark) {
  letter-spacing: 10px;
}
```
