### DISCUSSION TITLE
How to prevent "dancing" bulleted lists

### DISCUSSION THREAD

**Discussion by kethinov** [Zettlr/Zettlr#5543] [Show and tell]
Following up to this: https://github.com/Zettlr/Zettlr/discussions/4642

And addressing this comment: https://github.com/Zettlr/Zettlr/issues/4602#issuecomment-1737114816

Here is a solution:

```css
/* indent lists further than the default of ~1 character */
.cm-line > span.cm-list:first-of-type:not(.cm-meta):not(.cm-code-mark) {
  letter-spacing: 10px;
}

/* prevent "dancing" bulleted lists */
.cm-line > * {
  vertical-align: top;
}

/* prevent "dancing" bulleted lists */
.cm-list.cm-content-span.cm-code-mark.cm-meta, .rendered-bullet {
  display: inline-block;
  text-indent: 0;
  width: 10px;
}
```
