### DISCUSSION TITLE
How to make Zettlr feel more like Typora

### DISCUSSION THREAD

**Discussion by kethinov** [Zettlr/Zettlr#5546] [Show and tell]
Expanding on work I did [here](https://github.com/Zettlr/Zettlr/discussions/4642) and [here](https://github.com/Zettlr/Zettlr/discussions/5543), below is a custom set of CSS that will make a series of tweaks to Zettlr to make it look and feel more like Typora:

Features:

- Underlined links
- Spaced out bulleted lists more (derived from https://github.com/Zettlr/Zettlr/discussions/4642)
- Made headings look more like Typora
  - Removed indentation
  - Altered font sizes
  - Moved heading level marker to the right and made it invisible by default; you can still access it by hovering over the right edge
- Fixed the "dancing" bulleted lists bug (derived from https://github.com/Zettlr/Zettlr/discussions/5543)
- Added support for horizontal rules styled like Typora's
- Altered inline code blocks to look like Typora's
- Filed issue to request padding on multi-line code blocks: https://github.com/Zettlr/Zettlr/issues/5544
- Filed issue to request spell checking behavior that more closely resembles Typora's: https://github.com/Zettlr/Zettlr/issues/5545
- Added support for both light mode and dark mode

```css
/* dark scrollbar in dark mode */
body.dark {
  scrollbar-color: #666 #000;
}

/* underline links */
.cm-link {
  text-decoration: underline;
}

/* space out bulleted list items more */
.cm-line:has(.cm-list.cm-content-span.cm-code-mark.cm-meta, .rendered-bullet) {
  padding-top: 10px;
}

/* indent lists further than the default of ~1 character */
.cm-line > span.cm-list:first-of-type:not(.cm-meta):not(.cm-code-mark) {
  letter-spacing: 10px;
}

/* remove indentation of headings */
.size-header-1, .size-header-2, .size-header-3, .size-header-4, .size-header-5, .size-header-6 {
  position: relative;
  padding: 0 !important;
}

/* move heading level marker to the right */ 
.heading-tag {
  position: absolute;
  right: 0;
  padding: 0 !important;
}

/* alter hover behavior */
.heading-tag:hover {
  background: none !important;
}

/* reveal heading level when you hover over the right side */
.heading-tag:hover span {
  color: #ccc !important;
}

/* but hide it by default */
.heading-tag span {
  color: transparent !important;
}

/* better heading font-sizes and aesthetics */
.size-header-1 {
  font-size: 1.8em !important;
  border-bottom: 1px #ddd solid;
}
.dark .size-header-1 {
  border-bottom: 1px #555 solid;
}
.size-header-2 {
  font-size: 1.5em !important;
  border-bottom: 1px #ddd solid;
}
.dark .size-header-2 {
  border-bottom: 1px #555 solid;
}
.size-header-3 {
  font-size: 1.5em !important;
}
.size-header-4 {
  font-size: 1.3em !important;
}
.size-header-5 {
  font-size: 1.175em !important;
}
.size-header-6 {
  font-size: 1em !important;
}

/* prevent "dancing" bulleted lists */
.cm-line > * {
  vertical-align: top;
}

/* prevent "dancing" bulleted lists */
.cm-list.cm-content-span.cm-code-mark.cm-meta, .rendered-bullet {
  display: inline-block;
  text-indent: 0;
  width: 10px;
}

/* more beautiful code blocks */

/* inline code blocks */
span.code {
  background-color: #f3f4f4;
  color: #383838 !important;
  border: 1px #e7eaed solid;
  border-radius: 5px;
  padding: 3px;
}
.dark span.code {
  background-color: #333;
  color: #eee !important;
  border: 1px #555 solid;
}

/* add support for horizontal rules */
.cm-hr {
  display: inline-block;
  width: 100%;
  line-height: 0.25;
  color: transparent !important;
  border-bottom: 2px #e7e7e7 solid;
}
.dark .cm-hr {
  border-bottom: 2px #666 solid;
}
```
