### ISSUE TITLE
HTML5 Export - text-align: justify

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1363]
## Description
When doing an HTML5 export, the following CSS gets included. Is it intentional, that the HTML5 export has `text-align: justify` set?
```css
  article p {
    hyphens: auto;
    text-align: justify;
  }
```

## Reproducing
Export to HTML5 and notice that the text is suddenly stretched.

## Expected behaviour
That it looks like it does in the editor. Or, if that's actually intentional, would "custom CSS for HTML5 exports" be a reasonable feature request?

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2
