### ISSUE TITLE
[Feature Request] Automatic Text Wrap

### ISSUE THREAD

**Issue by sims1253** [Zettlr/Zettlr#244]
It would be nice if there was the option to have an automatic text wrap.
Currently the lines are as wide as the whole writing area, which on my screen is almost twice as wide as I would consider comfortable to read. While I could line break all lines at a point, having an automated way of displaying the text in a certain width would make life easier.

**Comment by nathanlesage** [comment]
While Zettlr tries to stick to the 45-55 characters per width on all devices, especially large screens may still face issues. Please provide the following information so that I can have a look at the breakpoints and add a measurable for your screen width:

- Your screen size in pixels
- The margins left and right needed to make the text appear good on your screen size.

Until the fixes are shipped with a new release, Custom CSS will solve your problems. Simply use the following:

```css
#editor .CodeMirror { margin-left: 250px; }
#editor .CodeMirror .CodeMirror-scroll { padding-right: 250px; }

#editor .CodeMirror-fullscreen { margin-left: 600px !important; }
#editor .CodeMirror-fullscreen .CodeMirror-scroll { padding-right: 600px !important; }
```

Replace the Pixel sizes (`250px` and `600px`) with different values to determine how good it looks.

If you're satisfied, please tell me the widths you've used for your screen size, so I can add them permanently to the User Interface!

**Comment by sims1253** [comment]
1920 x 1200 Screen.
This would make the normal mode width similar to the distraction free width (which I like):
```
#editor .CodeMirror { margin-left: 405px; }
#editor .CodeMirror .CodeMirror-scroll { padding-right: 405px; }

#editor .CodeMirror-fullscreen { margin-left: 600px !important; }
#editor .CodeMirror-fullscreen .CodeMirror-scroll { padding-right: 600px !important; }
```

Thanks for the quick reply :) :+1:

**Comment by chchen2021** [comment]
> ```css
> #editor .CodeMirror-fullscreen { margin-left: 600px !important; }
> #editor .CodeMirror-fullscreen .CodeMirror-scroll { padding-right: 600px !important; }
> ```

In Zettlr 2.1.0, I was trying to customize the max text width of the distraction-free mode using the above css code, but could not get it to work. The normal mode can be changed as suggested above.

**Comment by chchen2021** [comment]
This css works. Both `#editor.fullscreen` and `!important` are needed. 
```css
#editor.fullscreen .CodeMirror-fullscreen { margin-left: 600px !important; }
#editor.fullscreen .CodeMirror-fullscreen .CodeMirror-scroll { padding-right: 600px !important; }
```

@nathanlesage I suggest an update to the help page on [Custom CSS](https://docs.zettlr.com/en/core/custom-css/). 

By the way, the distraction-free mode offers an elegant solution to my earlier question: "[Maximum text width accounting for sidebar toggle](https://github.com/Zettlr/Zettlr/discussions/2516)". I will post further discussions under that thread.
