### ISSUE TITLE
[Bug] Keep math as-is when exporting to markdown

### ISSUE THREAD

**Issue by MoetaYuko** [Zettlr/Zettlr#2928]
### Description

https://github.com/Zettlr/Zettlr/commit/1259f357b2fca3f82462f1e6a29794e5e02cea33 implemented markdown export to strip yaml headers and expand citations, etc.

However, I notice that pandoc is also trying to process math expressions, resulting in unusable processed md files. See the example below for details.

### Reproducing

Here's a sample input text with inline math, display math, and citation.
```
Random citation[@kipfSemiSupervisedClassificationGraph2017] and inline math $\mathbb{R}^{c \times d}$
$$
\mathcal{L} = \frac{a}{b} \in \mathbb{R}^{c \times d}
$$
```
and the exported one looks like this:
```
Random citation\[1\] and inline math ℝ<sup>*c* × *d*</sup>
$$
\\mathcal{L} = \\frac{a}{b} \\in \\mathbb{R}^{c \\times d}
$$

<div id="refs" class="references csl-bib-body">


<div id="ref-kipfSemiSupervisedClassificationGraph2017"
class="csl-entry">

<span class="csl-left-margin">\[1\] </span><span
class="csl-right-inline">T. N. Kipf and M. Welling, “Semi-Supervised
Classification with Graph Convolutional Networks,” *arXiv:1609.02907
\[cs, stat\]*, Feb. 2017, Accessed: Apr. 23, 2021. \[Online\].
Available: <http://arxiv.org/abs/1609.02907></span>

</div>

</div>
```
From which we observe that:
1. pandoc is trying to add escape characters everywhere, including those in math environments. As a result, these tex commands are no longer recognized and thus can't be rendered correctly.
2. inline maths are converted to Unicode characters + HTML tags, this is pretty much undesired.

Meanwhile, is the HTML code around citations by design? I'd love to have plain text for them, is it possible to configure this?

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Arch

**Comment by nathanlesage** [comment]
All of what you describe is possible to configure using Pandoc's defaults. It may be somewhat tricky, but it certainly does the job.

> I'd love to have plain text for them, is it possible to configure this?

Here's just a quick glance of what is possible:

```yaml
reader: markdown
writer: gfm+raw_html # Remove '+raw_html' if you don't want raw HTML in the export
# Replace +raw_html with '+raw_tex' if you want TeX equations to be retained
self-contained: false
variables: {}
metadata-files: []
bibliography: []
filters:
- type: citeproc # Remove that if you don't want citations to be processed
section-divs: true
eol: lf
strip-comments: false
ascii: false
fail-if-warnings: false
```

For anything else, please consult the Pandoc manual: https://pandoc.org/MANUAL.html
