### ISSUE TITLE
[Bug] Table of Contents not working in HTML (and `PDF Document`)

### ISSUE THREAD

**Issue by backpack5689** [Zettlr/Zettlr#3084]
# Description

Hello!

I am currently having an issue with exporting a PDF using the yaml flag `toc`.

It appears to be creating the area, since when I set the `toc-title` to equal something, it will display that value, it will not create a table of contents.

Is there any way to fix this with the next update? I am working on a massive document for work, and need to include a table of contents.

Here is my full YAML frontmatter for those wondering:

```yaml
---
title: Runbooks
author: XXXXXXXXXXXXXXX
date: January 25th, 2022
toc: true
toc-depth: 2.0
toc-title: Runbooks Available
linkcolor: blue
---
```

# Reproducing

Attempt to export a .md to .pdf using the `toc` flag

# Zettlr version

Stable

# Your platform

Windows 10

# Architecture

Intel x64

**Comment by nathanlesage** [comment]
Are you exporting using `PDF Document` or `PDF (LaTeX)`? The latter one is the more advanced and recommended method, and I just tested it out, a table of contents should export fine.

**Comment by backpack5689** [comment]
I don't have the ability to install LaTeX on my work machine, so I am using `PDF Document` with the built in Pandoc.

Maybe this is something we could add to the built in version?

**Comment by nathanlesage** [comment]
In theory it should work, so the bug report is definitely valid and we'll need to have a look at that — because *in theory* a ToC should also be possible in HTML exports :D

**Comment by backpack5689** [comment]
Awesome! If there's some way I can help test or anything please let me know!

**Comment by nathanlesage** [comment]
@backpack5689 I think I may already have found the "error". The default default values deactivate the ToC (which makes sense for HTML files):

![image](https://user-images.githubusercontent.com/17251683/151214720-7a89c759-7650-4997-a697-7dbbc86ce8af.png)

This setting overrides the YAML frontmatter, so either remove it completely (which allows you to steer this per file), or set it to true (so that every file will always have a ToC).

Could you check back in if that solves this?

**Comment by backpack5689** [comment]
Sadly not.

I tried removing it within both the HTML and PDF, but it still isn't working. I tried to use the following YAML:
```yaml
title: Runbook
author: AO Smith Security Team
date: January 26th, 2022
linkcolor: blue
toc: enabled=true
toc-depth: 2
toc-title: Table of Contents
```
Which resulted in the following export (the "Topics" is an h1 that should be showing up in a toc):
![image](https://user-images.githubusercontent.com/47483901/151226339-2d8430aa-e55f-45ff-8852-24e5988c9fe3.png)
