### ISSUE TITLE
[Enhancement] Add hover style to file tree/list items

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3094]
### Description

Add a hover effect when hovering over items in the file tree and the file list with the mouse. I think it's nice to have some kind of visual feedback when selecting files/folders.

### Proposed Changes

I have identified the following three properties that would need the CSS `hover` selector:
```css
body div.list-item-wrapper div.list-item:hover {
  background-color: red; /* color tbd */
}

body div.tree-item-container .tree-item.selected .display-text:hover {
  background-color: red; /* color tbd */
}

body .tree-item .display-text:hover {
  background-color: red; /* color tbd */
}
```

On my machine (Linux), these three seem to do their job ~~(in light and dark mode)~~, as you can see in the video below (using red color as an example).

**Edit**: The stylings above do not all work in both modes. The first style doesn't work in dark mode, unless `body.dark` is used; the second and third styles, however, also work in dark mode.

Do we need to add stylings for the different platforms, due to different color requirements? Or could we apply the same hover color (e.g., some grayscale value) on all platforms?

### Caveats

~~None!~~ See comments below.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [X] macOS
- [X] Linux

### Operating System Version

Linux manjaro 5.14.21-2

### Additional Information

https://user-images.githubusercontent.com/18646029/151447257-0db295fa-3e1a-4be4-8c02-b22bcafdf771.mp4
