### ISSUE TITLE
[Bug] Hyphenation not working properly using PDF (LaTeX) export

### ISSUE THREAD

**Issue by vtcarlino** [Zettlr/Zettlr#3182]
### Description

Hyphenation rules defined by document language aren't taken into account when exporting to PDF LaTeX. In my case, adding `lang: fr` in the YAML front-matter or in the defaults file doesn't affect the hyphenation.

Zettlr export :
![Capture d’écran 2022-02-12 à 12 43 17](https://user-images.githubusercontent.com/24810357/153709875-42f160c1-4c48-4f18-9e8a-f6d5d8eb8b69.png)

Expected behaviour (Pandoc CLI export) :
![Capture d’écran 2022-02-12 à 12 42 59](https://user-images.githubusercontent.com/24810357/153709869-5bd924b0-eb6c-4627-b48e-c892fcc353a9.png)

### Reproducing

1. Set `lang: fr` in the YAML frontmatter or in the PDF defaults file
2. Export to PDF LaTeX

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

macOS Catalina 10.15.7

**Comment by nathanlesage** [comment]
Would you mind having a look at the corresponding defaults file? There is a good possibility I have overridden a Pandoc default there out of good intentions that is now shooting you in the knee 👀

**Comment by vtcarlino** [comment]
Yes sure, here it is. As you can see, I only added a few variables. The rest is default (litteraly): 

```
# ZETTLR DEFAULTS FILE
# ====================
# Conversion: Markdown --> PDF (requires TeX suite installed)
# More info: https://pandoc.org/MANUAL.html
reader: markdown
writer: pdf
self-contained: true
variables:
  author: "Vincent Carlino"
  papersize: a4
  lang: fr
metadata-files: []
include-before-body: []
include-after-body: []
include-in-header: []
bibliography: []
filters:
- type: citeproc
file-scope: false
top-level-division: default
pdf-engine: xelatex # Change this if you want to use a different engine.
dpi: 72
toc: false
toc-depth: 2
number-sections: false
number-offset:
- 0
- 0
- 0
- 0
- 0
- 0
shift-heading-level-by: 1
section-divs: true
identifier-prefix: ''
title-prefix: ''
eol: lf
strip-comments: false
indented-code-classes: []
ascii: false
default-image-extension: .jpg
highlight-style: pygments
tab-stop: 4
preserve-tabs: false
fail-if-warnings: false
```

**Comment by nathanlesage** [comment]
Quick question: I just saw that you added `lang: fr` to the `variables` section — isn't that something that belongs into the `metadata` section? As far as I know `variables` means literal variables inside the template, but `lang` is a metadata value. Would you mind trying this out?

**Comment by vtcarlino** [comment]
Thé difference between `variables` and `metadata` isn’t clear to me. I just followed [this tip](https://docs.zettlr.com/en/core/defaults-files/) from Zettlr’s documentation:

> If you regularly export into, say, French, it might make sense to set the lang property directly in your defaults files to fr so that files are being exported using that locale by default. 

Where should I put the `lang` value?

**Comment by nathanlesage** [comment]
> Where should I put the lang value?

Given the YAML file above, something like this:

```yaml
variables:
  author: "Vincent Carlino" # I'm not sure whether this isn't also metadata
  papersize: a4 # This is definitely a variable, so it's in the right spot
metadata:
  lang: fr
```

The differentiation between `metadata` and `variables` is weird, indeed. But as far as I understood, variables are more what the template itself can use (more styling information such as papersize, fonts, margins, etc.) whereas metadata definitely have some connection to the document's content (such as the language, author name (?) and so)
