### ISSUE TITLE
[Bug] Fragment identifier breaks path of images

### ISSUE THREAD

**Issue by robsonsobral** [Zettlr/Zettlr#3236]
### Description

There's a hack to align images using fragment identifiers.

```css
img[src$='#float'] {
    float: left;
    clear: left;
    margin-right: 0.75em;
    margin-bottom: 1.5em;
}
```

Unfortunatelly, the hack breaks the load of images on Zettlr.

### Reproducing

Add Any fragment identifier to the end of an image path, like `![](image.png#fragment)`

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11
