### ISSUE TITLE
Mermaid diagram default style

### ISSUE THREAD

**Issue by dgcom** [Zettlr/Zettlr#3427]
### Description

Mermaid diagram should use default style regardless of the theme, unless overridden.

Consider this simplified diagram:
```mermaid
flowchart LR
    subgraph app_folder1[App folder]
        sink_prod1[\Prod project:\nsink & filter/]
    end
    subgraph shared_services["Services"]
            pubsub_prod[/"PubSub Prod\ntopic/subscription"\]
    end
    sink_prod1 -.->|writer identity| pubsub_prod
```

GitHub and many other editors will render it correctly and using default styling regardless of editor theme.
Zettlr should behave the same, but instead it applies a custom, dark theme to it and custom text indents cause text to be cut out:

![image](https://user-images.githubusercontent.com/7088388/165887427-817631a8-e003-4963-aae3-f8db624fac42.png)

This does not play well with any of the default light themes.

I saw that there was a pull request last year (#2199 ) which was trying to improve styling... It was closed due to inactivity, sadly, but still - default behavior should render such diagrams correctly, using default style and then any changes should be built based on these defaults.

### Reproducing

Add diagram code block and observe/compare the rendering:

        ```mermaid
        flowchart LR
            subgraph app_folder1[App folder 1]
                sink_prod1[\Prod project 1:\nsink & filter/]
            end
            subgraph shared_services["Shared Services folder"]
                    pubsub_prod[/"PubSub Prod\ntopic/subscription"\]
            end
            sink_prod1 -.->|writer identity| pubsub_prod
        ```

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10, Ubuntu 20.04

**Comment by nathanlesage** [comment]
We don't knowingly modify any of mermaid's themes. We do use the `dark` theme, yes, but it should not be modified.

As a first step of remidification I can offer you to switch themes based on the app's theme (i.e. light or dark mermaid theme depending on the surrounding mode). That should be fairly easy and you are absolutely right that a dark mode within a light environment looks weird.

Then, with regard to the cut-off text, I can have a look, but I can't promise anything since I don't use that feature myself.

**Comment by nathanlesage** [comment]
I tried out switching the themes but it didn't work. I guess that's the reason why it looks so static. Mermaid is a little bit buggy.

**Comment by dgcom** [comment]
I am using mermaid in at least 3 other md editors - VS Code, GitHub and Joplin. First two have no issue making it to follow light/dark theme and Joplin keeps default (light) theme in dark mode as well, which I find acceptable.
But dark mermaid with light editor theme? Does not fit at all.

**Comment by leo-hstone** [comment]
I was playing around with custom CSS to fit the diagram theme better to my theme. I just use the light theme. Maybe this helps you (or others) in the meantime. (Disclaimer: I don't understand css at all, this is just trial-and-error)

```css
/* colors - only primary relevant */
:root {
  --c-primary: #063D79;
  --c-primary-shade: #042a54;
  --c-secondary: var(--blue-0);
  --c-secondary-shade: var(--blue-1);
}

/*mermaid-diagrams*/
/*use light background color (or dark in dark mode)*/
body #editor .CodeMirror .mermaid-chart svg{
  	background-color: var(--grey-0);
}
body.dark #editor .CodeMirror .mermaid-chart svg{
  	background-color: var(--grey-6);
}
/* clusters are medium grey*/
body #editor .CodeMirror .mermaid-chart * .cluster rect{
  fill: var(--grey-1);
  stroke-width: 0px;
}
body #editor .CodeMirror .mermaid-chart * .cluster .label{
  color: black;
}
body.dark #editor .CodeMirror .mermaid-chart * .cluster rect{
  fill: var(--grey-5);
  stroke-width: 0px;
}
/* egde label */
body #editor .CodeMirror .mermaid-chart * .edgeLabel{
  background-color: white;
  fill: white;
  color: black;
}
body #editor .CodeMirror .mermaid-chart * .edgeLabel .label{
  color: black;
}

body #editor .CodeMirror .mermaid-chart * .node rect,
body #editor .CodeMirror .mermaid-chart * .node polygon,
body #editor .CodeMirror .mermaid-chart * .node ellipse,
body #editor .CodeMirror .mermaid-chart * .node circle{
  fill: white;
  stroke-width: 1px;
}
/*lighter text color*/
body #editor .CodeMirror .mermaid-chart * .node .label{
  color: black;
}
/*arrow lines and heads are green*/
body #editor .CodeMirror .mermaid-chart * .marker,
body #editor .CodeMirror .mermaid-chart * .edgePath,
body #editor .CodeMirror .mermaid-chart * .path,
body #editor .CodeMirror .mermaid-chart * .flowchart-link {
  stroke: var(--c-primary);
  fill: var(--c-primary);
}
```
