### ISSUE TITLE
Draw horizontal rulers

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#3444]
### Description

Draw horizontal rulers with CSS. Here's an example from Nextcloud Notes:

![image](https://user-images.githubusercontent.com/1702193/166441189-34c2a147-abf6-447c-9b40-711c4e452b55.png)

### Proposed Changes

Add some styling

### Caveats

It's a simple way to make documents more pleasant to read. It seems simple enough to implement, but it's not. 

I've tried implementing this using CSS, and while it works in some browsers, it won't work in Chrome/Electron.

While horizontal rulers are marked with the `cm-hr` class, this is only as wide as the written part of the line (e.g. `---`), but you'd want to draw a full width horizontal rule. The first full width element is the `CodeMirror-line`.

- `pre.CodeMirror-line`
    - `span`
        - `span.cm-hr`

The `has:` CSS selector for applying styles to parents on conditional children is [proposed but not implemented](https://chromestatus.com/feature/5794378545102848) in Chrome/Electron yet, AFAIK.

Perhaps someone with better CSS-foo or CodeMirror insights has an idea I hadn't thought of. Otherwise I think, if this is going to be implemented, it would require [something in code](https://www.youtube.com/watch?v=cGpawfJHKwI).

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Linux Mint 20.2 AKA Ubuntu 20.04.2

**Comment by kyaso** [comment]
I have the following style applied in my custom.css:
```css
/* Horizontal rule style */
body #editor .CodeMirror .cm-hr {
    display: inline-block;
    width: 100%;
    line-height: 0.25;
    color: transparent;
    background: linear-gradient(90deg, var(--c-primary),  #7beac3, transparent);
}
```

Output:
![grafik](https://user-images.githubusercontent.com/18646029/166451384-deba143a-97bc-427a-bbd0-b211d32e4d4d.png)

Maybe that helps!
