### ISSUE TITLE
Active tab styling color is overridden

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#3445]
### Description

Active tab is intended to have a color marking. The code is there:

```css
body.linux div#tab-container div[role="tab"].active {
    border-bottom: 3px solid var(--system-accent-color, --c-primary);
}
```

But it does not work (using the `berlin-dark` theme) because it is overridden by the non-active `border-color` setting.

### Reproducing

![image](https://user-images.githubusercontent.com/1702193/166462108-6f67a129-d41c-451f-b08f-0f22b1811091.png)

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Mint 20.2 AKA Ubuntu 20.04.2

### Additional Information

It can be fixed using `!important`:

```css
body.linux div#tab-container div[role="tab"].active {
    border-bottom: 3px solid var(--system-accent-color, --c-primary) !important;
}
```

![image](https://user-images.githubusercontent.com/1702193/166462674-c21c4bf3-107b-4950-a45a-959f6a06539d.png)

**However, I can't find the location of this CSS in the source files.** And it's driving me crazy, because I sextuple-checked all theme files and it _must_ be there, no?

As a workaround, I've overridden this in `custom.css`. But judging from the code, this is supposed to work, so if you know where this is defined, it's probably very easy to include it with any commit. :grin:
