### ISSUE TITLE
Chinese title not displayed instead of filename

### ISSUE THREAD

**Issue by sati-bodhi** [Zettlr/Zettlr#3976]
### Description

I use the default id as filename and set `Zettlr` to "Display files using title if applicable". Chinese titles, however, don't seem to be detected and I am stuck with the filename which is not very helpful for navigation. 

### Reproducing

1. Set "General" tab to `"Display files using title if applicable"`.
2. Paste the following `yaml` and save a new file as its default filename. 
3. Title will not be displayed in place of filename by file manager. 

```yaml
---
title: 史之象形
bibliography: ~/zettlr/bibliography/paleography.json
lang: zh-TW
reference-section-title: 參考文獻
keywords:
	- 文字學
	- 本義
	- 字形分析
---
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04

### Additional Information

![Screenshot from 2022-12-08 00-13-36](https://user-images.githubusercontent.com/7592695/206231893-abcb5792-cff0-47d8-a543-6a3efaa8a4d6.png)
