### ISSUE TITLE
[ENHANCEMENT] Style "fat" cursor in overwrite mode to indicate it's active

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#410]
## Description

While for the first time really working in production with Zettlr on a Windows machine, I have been reminded that there's an insert key on Windows keyboards, and I was additionally reminded that it's hard to determine whether you accidentally activated that mode (Word and LibreOffice at least give you a small status bar indication, although easily to be overlooked). Zettlr currently enables the overwrite mode but you have to realise you're in overwrite, b/c there's no indication.

## Reproducing

Switch on Overwrite by pressing `Ins` and feel cheated upon.

## Expected behaviour

There's a need for an indication.

**Screenshots**

## Platform
 - OS: Windows + Linux
 - Zettlr Version: All versions, actually.
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information

CodeMirror is nice and gives us an additional class to target "fat" cursors when in overwrite mode, to style it differently (especially as block mode). This CSS can be used to make it work:

```css
.CodeMirror-cursors.CodeMirror-overwrite .CodeMirror-cursor {
  width: auto;
  border: 1px solid #333;
  background-color: rgba(255, 200, 200, 0.5);
  z-index: 1;
}
```

Only the width is not working right now, but I'm sure there's a solution to that. If anybody has an idea, please come forward!
