### ISSUE TITLE
Tab highlighting irritating

### ISSUE THREAD

**Issue by Himra** [Zettlr/Zettlr#4152]
### Description

The current highlighting of the active tab irritates me regularly.
At the moment it looks like this for me:

![2023-02-15 07_59_04-Window](https://user-images.githubusercontent.com/15324567/218961725-55e22767-8d07-4e00-b6fb-044e53f86b10.png)

### Proposed Changes

My suggestion would be to close the frame around the active tab not only on the right and left, but also on the top and match the colors of the inactive area to the area on the left or, as in the second example, to the background color of the top menu bar.

![image10](https://user-images.githubusercontent.com/15324567/218961803-92ccc59d-50c3-4202-ace5-9fa1f157aa91.png)

![image10_](https://user-images.githubusercontent.com/15324567/218961858-408dd33e-cad7-48b1-a810-c203d0c1b655.png)

This would, in my opinion, prevent irritation and improve quick usability.

### Caveats

Can I solve this myself via custom templates?

### Do you Wish to Attempt Implementing this Yourself?

Yes if it is solvable via CSS

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

### Additional Information

Thanks for the great program

VG Himra

**Comment by Himra** [comment]
Hello together,

before I wrote this issue, I was working with custom.css, and it did not work.
The examples in the documentation and also the examples in the discussion don't work at all or only partially and not with the tabs.

Tried around again for a longer time and got it to work. The documentation seems to be outdated.

Here is my example:


```css
body.dark.win32 div.tab-container {
  background-color: #323232;
  border-top: 1px solid var(--grey-3);
  border-bottom: 1px solid var(--grey-3);
}

body.win32.dark div.tab-container div[role="tab"]:last-child {
  border-right: 1px solid var(--grey-3);
}

body.win32.dark div.tab-container div[role="tab"].active {
  background-color: var(--c-primary);

}
```

Greetings Himra

**Comment by exanrauzer** [comment]
Great tweak!

**Comment by Himra** [comment]
For Zettlr version 3

```css
body.dark.win32 div.tab-container {
  background: linear-gradient(
    to top,
    var(--grey-3) 1px,
    #333333 1px,
    #333333 100%
  );
}

body.win32 div.tab-container div[role="tab"]:not(:last-child) {
  border: none;
}

body.win32.dark div.tab-container div[role="tab"]:hover {
  background-color: #14141e;
}

body.win32.dark div.tab-container div[role="tab"].active {
  border-top: 1px solid var(--grey-3);
  border-inline: 1px solid var(--grey-3);
  background-color: #14141e;
}
```
