### ISSUE TITLE
CSS class `cm-selectionBackground` is not visible when selecting code inside a `plain`, `text` or empty code block

### ISSUE THREAD

**Issue by guzmandrade** [Zettlr/Zettlr#4559]
### Description

The base theme `berlin`, from which the other take these CSS rules, does not highlight characters when selecting text inside an inline code word, like `this` or when using a multiline code block without language, like

```
this
```
which is the same as using `plain`, `text`, and probably others that apply the classes `cm-monospace cm-monospace` to the code lines.

### Reproducing

On any document, on dark or light modes, create an inline word or sentence using the backtick character like 
<pre>
`this` 
</pre>
or with triple backtick without language or using `plain` or `text` for a multiline code block, like
<pre>
```plain
this plain block
```
</pre>
or
<pre>
```text
this text block
```
</pre>
or
<pre>
```
this non-language code block
```
</pre>

and after creating any of these elements, select characters or words, and they won't be highlighted.

### Zettlr Version

Right off the develop branch

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Linux (Ubuntu 23.04) and macOS (Ventura 13)

### Additional Information

Screenshots:

not highlighting:
![not highlighting](https://github.com/Zettlr/Zettlr/assets/7761960/7c52ce62-489f-48f0-a18d-6ed696dc2b55)

classes applying
![claases applying](https://github.com/Zettlr/Zettlr/assets/7761960/36e5415c-12b2-489b-a0bc-a0a8d8e73267)

I will post a PR with CSS changes to the theme `berlin`. I understand I can apply my own CSS classes to Zettlr. However, the fix I was able to create won't work ok both dark and light themes simultaneously. This is my snippet for the light theme (which doesn't work on the dark theme)

```css
:root {
  --green-selection:       rgba(180, 240, 170, 0.6);
  --green-selection-dark:  rgba( 90, 170,  80, 0.6);
  --blue-selection:        rgba(200, 220, 240, 0.6);
  --blue-selection-dark:   rgba( 29,  55, 134, 0.6);
}

body .main-editor-wrapper .cm-editor .code-block-line-background,
body .main-editor-wrapper .cm-editor .cm-monospace {
  background-color: rgba(238, 238, 238, 0.5);
}
```  

Thank you.
