### ISSUE TITLE
Bielefeld theme sets font-family with !important

### ISSUE THREAD

**Issue by jzeneto** [Zettlr/Zettlr#4719]
### Description

The Bielefeld theme sets the font family using `!important`, which, according to own [Zettlr documentation](https://docs.zettlr.com/en/advanced/custom-css/#writing-css-for-zettlr), "(...) is widely regarded as bad practice". Using debug mode > developer tools, I see the theme code snippet in question is as follows:

```css
body .main-editor-wrapper .cm-scroller {
    font-family: 'Liberation Mono', Consolas, Menlo, monospace !important;
}
```

Due to this, I have to also use `!important` to change font family when using this theme.

### Reproducing

1. open Zettlr
2. select Bielefeld theme in Preferences > Display
3. activate debug mode
4. open developer tools
5. select the editor element, and find the CSS rule listed above

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux Manjaro, Gnome 44
