### ISSUE TITLE
[Citing] Bibliography in YAML form: NO_PRINTED_FORM in place of year

### ISSUE THREAD

**Issue by jzeneto** [Zettlr/Zettlr#4847]
### Description

When using a bibliography in YAML format (generated from Zotero using [Better BibTeX "Better CSL YAML" export](https://retorque.re/zotero-better-bibtex/installation/bundled-translators/index.html#export)), citation years are rendered as the string NO_PRINTED_FORM, or not rendered at all. (Using JSON as format works properly.)

Example: using the following citation:

```yaml
- id: oidaAtorInvisivel2007
  author:
    - family: Oida
      given: Yoshi
  citation-key: oidaAtorInvisivel2007
  issued:
    - year: 2007
  publisher: Via Lettera
  publisher-place: São Paulo
  title: O ator invisível
  type: book
```

- citing as `[@oidaAtorInvisivel2007]` renders solely the author: `(Oida)`, but should render as `(Oida 2007)`
- citing as `[-@oidaAtorInvisivel2007]` renders as `[NO_PRINTED_FORM]` with citation usual background; note the brackets. Should render as `2007`

### Reproducing

1. In Zotero, use Better BibTeX to make an [export](https://retorque.re/zotero-better-bibtex/installation/bundled-translators/index.html#export) using "Better CSL YAML" as format. (Or simply save the citation example above as a .yaml file.)
2. In Zettlr, use that bibliography file and try to cite one of the works:
  - using `[@Author2023]` renders as `(Author)`
  - using `[-@Author2023]` renders as `[NO_PRINTED_FORM]` (note the brackets instead of parentheses)

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3 (UUID: 08717594-1129-4aac-a472-15b327b835b1)

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro GNOME

### Additional Information

Installed through Manjaro repositories.
