### ISSUE TITLE
Incorrect IME pop-up position

### ISSUE THREAD

**Issue by ryota-abe** [Zettlr/Zettlr#537]
## Description
When I input Japanese text using IME(Input Method Editor), the suggestions pop-up overlaps the text I'm typing.
![image](https://user-images.githubusercontent.com/15438757/74338475-99b75580-4de5-11ea-8344-d10e15cc0c9c.png)

## Reproducing
1. [Install Japanese MS-IME on Windows 10](https://www.coscom.co.jp/learnjapanese801/msime_win10_en1.html).
2. Type something in the editor. (e.g. "konnnichiha")

## Expected behaviour
IME pop-up appears in place and do not hide input text.

## Platform
 - OS and version: Windows 10 Home 1903
 - Zettlr Version: 1.6.0-beta.2
 - Screen Resolution: 1366x768

## Additional information
I'm using the following custom CSS to work around this problem
```css
.CodeMirror-wrap > div > textarea {
  font-size: 1.6em;
  letter-spacing: -0.4em;
  font-family: 'Segoe UI', sans-serif;
}
```
It looks like this:
![image](https://user-images.githubusercontent.com/15438757/74338974-81940600-4de6-11ea-909d-4070a1085232.png)
