### ISSUE TITLE
Appearence inconsistency Fedora versus Windows

### ISSUE THREAD

**Issue by KamoD-a** [Zettlr/Zettlr#5473]
### Description

The appearence of Zettlr on Fedora looks completey different from Windows.
![grafik](https://github.com/user-attachments/assets/97fa2909-924d-4353-b3bc-0439d1427fa6)

The buttons have a distracting border around them.

On Windows, everything looks like it is advertised on your webpage
![grafik](https://github.com/user-attachments/assets/f619b615-2ed9-4003-a175-74ce8f510492)

I made my own custom css to get rid of this look (see additional information), but I wanted you to know, in case it is just a version issue and the newest version is not on Fedora. 

Thank you very much for your work. I just found Zettlr last night and I love the project option and the export functions are just what I am looking for. A great alternative to obsidian :) and it is open source 😄 great job :)

### Reproducing

We tried installing Zettlr on two different Fedora systems from the following channels:
- Download from your website
- github nightly release
- flatpak
The issue occured on all the Fedora versions.

On Windows it worked straight out of the box
- chocolatey (on windows)

### Zettlr version

3.2.3

### Installation Method

Other (please specify below)

### Installation Method (Other)

We tried these three ways to install it on two different Fedora systems- Download from your website - github nightly release - flatpak

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Fedora Linux 41 Workstation Edition

### Additional Information

My custom css file to fix the button look (and some additional color settings 😄):
```css
:root {
  --main-editor-color: #181818;
  --secondary-color: #323232;
  --accent-color: #e74c3c;
  --text-color: #d9d9d9;
  --project-color: #668cff;
  --system-accent-color: #71428a;
}

body.linux div#toolbar button {
    background-color: transparent;
    border: 1px solid var(--secondary-color) 
    border-radius: 4px;
}

span.cm-statusbar-item {
  border-color: var(--secondary-color) ;
}

body.linux.dark div.tab-container div[role="tab"] {
    border-color: #222;
    background-color: var(--secondary-color) ;
    border-radius: 5px 5px 0px 0px;
}
body.linux.dark div.tab-container div[role="tab"].active {
    background-color: var(--main-editor-color);
    border-bottom-color: var(--main-editor-color);
    z-position: 1;
}


body.linux.dark div.tab-container {
    background-color: var(--secondary-color);
}

body.dark .main-editor-wrapper {
    background-color: var(--main-editor-color);
    color: var(--text-color);
    font-size: 20px;
}

body.dark {
    color: var(--text-color);
    background-color: var(--main-editor-color);
    font-size: 20px;
}

ͼv .cm-scroller {
    color: var(--text-color);
    font-size: 20px;
    font-family: -apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, "Helvetica Neue", Helvetica, Ubuntu, Roboto, Noto, "Segoe UI", Arial, sans-serif;
}

body.linux.dark #file-tree {
    background-color: var(--main-editor-color);
    font-size: 15px;
}

body.dark div.tree-item-container .tree-item.project {
    color: var(--project-color);
}

.main-editor-wrapper .cm-content {
   padding-left: 7rem;
   padding-right: 10rem;
}

.ͼv .cm-url, .ͼv .cm-link, .ͼv .cm-code-mark, .ͼv .cm-zkn-tag, .ͼv .cm-zkn-link {
    color: var(--system-accent-color);
}

body.linux.dark input, body.linux.dark select, body.linux.dark textarea, body.linux.dark button {
    background-color: #333;
    color: var(--text-color);
}

body div.tab-container {
    border-bottom: 0px; 
}
```
