### ISSUE TITLE
Horizontal rules rendering in the editor

### ISSUE THREAD

**Issue by Noopss** [Zettlr/Zettlr#5563]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [ ] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Is it possible to render the horizontal rules directly in the editor, the same way they render in the documents exported.

### Example Workflow

Typing "***" or "---" render the horizontal rule in the editor, instead of letting only the characters as they are typed.

### Caveats

I don't think there will be any caveats

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by kyaso** [comment]
Hey! There is a way to achieve this using custom CSS. E.g.:
```css
body .main-editor-wrapper .cm-editor .cm-hr {
    display: inline-block;
    width: 100%;
    line-height: 0.25;
    color: transparent;
    background: linear-gradient(90deg, #1cb27e,  #7beac3, transparent);
}
```
renders as:
![image](https://github.com/user-attachments/assets/8e20b30a-328c-4e66-adb0-24843ad05883)
