### ISSUE TITLE
[ENHANCEMENT] Provide an option for hiding file tabs

### ISSUE THREAD

**Issue by SSLPP** [Zettlr/Zettlr#932]
## Description
Please provide an option for hiding the file tabs or an option to revert back to the v1.6 style. I find the colored tabs distracting (just a personal preference). 

# Platform

    OS and version: Win 10
    Zettlr Version: 1.7.0-beta11
    Screen Resolution:

**Comment by Amar0ks** [comment]
I agree. The interface looks a bit untidy anyway. 
In addition I would like to turn it off. Just hiding it will lead to many open tabs that consume performance I guess.  That and an option for "wysiwyg = true".

If it helps you this css snippet will hide the tabs:

```css
#document-tabs {
  height: 0px;
  border-bottom: 0px !important;
}
```
